<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DRACULA" failures="14" tests="16" name="Testing_Signin" time="173.718" errors="0" timestamp="2021-12-08T18:54:10 IST">
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidusernameValidPassword" time="3.733">
    <failure type="java.lang.AssertionError" message="expected [User Doesnt Exist!] but found [Login Success]">
      <![CDATA[java.lang.AssertionError: expected [User Doesnt Exist!] but found [Login Success]
at po.Po_Signin.SignIn_InvalidUsername_validPassword(Po_Signin.java:141)
at testcase.Testcase_Signin.signIn_userInvalidusernameValidPassword(Testing_Signin.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidusernameValidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidusernameValidPassword" time="5.75">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_InvalidUsername_validPassword(Po_Signin.java:145)
at testcase.Testcase_Signin.signIn_userInvalidusernameValidPassword(Testing_Signin.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidusernameValidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidusernameValidPassword" time="3.63">
    <failure type="java.lang.AssertionError" message="expected [User Doesnt Exist!] but found [Invalid Credentials]">
      <![CDATA[java.lang.AssertionError: expected [User Doesnt Exist!] but found [Invalid Credentials]
at po.Po_Signin.SignIn_InvalidUsername_validPassword(Po_Signin.java:141)
at testcase.Testcase_Signin.signIn_userInvalidusernameValidPassword(Testing_Signin.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidusernameValidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidusernameValidPassword" time="5.628">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_InvalidUsername_validPassword(Po_Signin.java:145)
at testcase.Testcase_Signin.signIn_userInvalidusernameValidPassword(Testing_Signin.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidusernameValidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userValidUsernameInvalidPassword" time="3.681">
    <failure type="java.lang.AssertionError" message="expected [User Doesnt Exist!] but found [Login Success]">
      <![CDATA[java.lang.AssertionError: expected [User Doesnt Exist!] but found [Login Success]
at po.Po_Signin.SignIn_validUsername_InvalidPassword(Po_Signin.java:120)
at testcase.Testcase_Signin.signIn_userValidUsernameInvalidPassword(Testing_Signin.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userValidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userValidUsernameInvalidPassword" time="5.671">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_validUsername_InvalidPassword(Po_Signin.java:124)
at testcase.Testcase_Signin.signIn_userValidUsernameInvalidPassword(Testing_Signin.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userValidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userValidUsernameInvalidPassword" time="10.599"/>
  <testcase classname="testcase.Testcase_Signin" name="signIn_userValidUsernameInvalidPassword" time="5.837">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_validUsername_InvalidPassword(Po_Signin.java:124)
at testcase.Testcase_Signin.signIn_userValidUsernameInvalidPassword(Testing_Signin.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userValidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_uservaliddata" time="3.698"/>
  <testcase classname="testcase.Testcase_Signin" name="signIn_uservaliddata" time="5.82">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_Validdata(Po_Signin.java:82)
at testcase.Testcase_Signin.signIn_uservaliddata(Testing_Signin.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_uservaliddata -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_uservaliddata" time="3.54">
    <failure type="java.lang.AssertionError" message="expected [Login Success] but found [Invalid Credentials]">
      <![CDATA[java.lang.AssertionError: expected [Login Success] but found [Invalid Credentials]
at po.Po_Signin.SignIn_Validdata(Po_Signin.java:78)
at testcase.Testcase_Signin.signIn_uservaliddata(Testing_Signin.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn_uservaliddata -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_uservaliddata" time="5.929">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_Validdata(Po_Signin.java:82)
at testcase.Testcase_Signin.signIn_uservaliddata(Testing_Signin.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_uservaliddata -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidUsernameInvalidPassword" time="4.004">
    <failure type="java.lang.AssertionError" message="expected [User Doesnt Exist!] but found [Login Success]">
      <![CDATA[java.lang.AssertionError: expected [User Doesnt Exist!] but found [Login Success]
at po.Po_Signin.SignIn_InvalidUsername_InvalidPassword(Po_Signin.java:99)
at testcase.Testcase_Signin.signIn_userInvalidUsernameInvalidPassword(Testing_Signin.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidUsernameInvalidPassword" time="5.843">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_InvalidUsername_InvalidPassword(Po_Signin.java:103)
at testcase.Testcase_Signin.signIn_userInvalidUsernameInvalidPassword(Testing_Signin.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidUsernameInvalidPassword" time="3.86">
    <failure type="java.lang.AssertionError" message="expected [User Doesnt Exist!] but found [Invalid Credentials]">
      <![CDATA[java.lang.AssertionError: expected [User Doesnt Exist!] but found [Invalid Credentials]
at po.Po_Signin.SignIn_InvalidUsername_InvalidPassword(Po_Signin.java:99)
at testcase.Testcase_Signin.signIn_userInvalidUsernameInvalidPassword(Testing_Signin.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidUsernameInvalidPassword" time="5.687">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_InvalidUsername_InvalidPassword(Po_Signin.java:103)
at testcase.Testcase_Signin.signIn_userInvalidUsernameInvalidPassword(Testing_Signin.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidUsernameInvalidPassword -->
</testsuite> <!-- Testing_Signin -->
