<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DRACULA" failures="14" tests="16" name="Testcase_Signin" time="165.603" errors="0" timestamp="2021-12-10T12:28:14 IST">
  <testcase classname="testcase.Testcase_Signin" name="signIn_uservaliddata" time="4.721"/>
  <testcase classname="testcase.Testcase_Signin" name="signIn_uservaliddata" time="5.656">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_Validdata(Po_Signin.java:82)
at testcase.Testcase_Signin.signIn_uservaliddata(Testcase_Signin.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_uservaliddata -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_uservaliddata" time="3.722">
    <failure type="java.lang.AssertionError" message="expected [Login Success] but found [Invalid Credentials]">
      <![CDATA[java.lang.AssertionError: expected [Login Success] but found [Invalid Credentials]
at po.Po_Signin.SignIn_Validdata(Po_Signin.java:78)
at testcase.Testcase_Signin.signIn_uservaliddata(Testcase_Signin.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn_uservaliddata -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_uservaliddata" time="5.761">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_Validdata(Po_Signin.java:82)
at testcase.Testcase_Signin.signIn_uservaliddata(Testcase_Signin.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_uservaliddata -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidUsernameInvalidPassword" time="4.114">
    <failure type="java.lang.AssertionError" message="expected [User Doesnt Exist!] but found [Login Success]">
      <![CDATA[java.lang.AssertionError: expected [User Doesnt Exist!] but found [Login Success]
at po.Po_Signin.SignIn_InvalidUsername_InvalidPassword(Po_Signin.java:99)
at testcase.Testcase_Signin.signIn_userInvalidUsernameInvalidPassword(Testcase_Signin.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidUsernameInvalidPassword" time="5.942">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_InvalidUsername_InvalidPassword(Po_Signin.java:103)
at testcase.Testcase_Signin.signIn_userInvalidUsernameInvalidPassword(Testcase_Signin.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidUsernameInvalidPassword" time="4.536">
    <failure type="java.lang.AssertionError" message="expected [User Doesnt Exist!] but found [Invalid Credentials]">
      <![CDATA[java.lang.AssertionError: expected [User Doesnt Exist!] but found [Invalid Credentials]
at po.Po_Signin.SignIn_InvalidUsername_InvalidPassword(Po_Signin.java:99)
at testcase.Testcase_Signin.signIn_userInvalidUsernameInvalidPassword(Testcase_Signin.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidUsernameInvalidPassword" time="5.713">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_InvalidUsername_InvalidPassword(Po_Signin.java:103)
at testcase.Testcase_Signin.signIn_userInvalidUsernameInvalidPassword(Testcase_Signin.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userValidUsernameInvalidPassword" time="3.715">
    <failure type="java.lang.AssertionError" message="expected [User Doesnt Exist!] but found [Login Success]">
      <![CDATA[java.lang.AssertionError: expected [User Doesnt Exist!] but found [Login Success]
at po.Po_Signin.SignIn_validUsername_InvalidPassword(Po_Signin.java:120)
at testcase.Testcase_Signin.signIn_userValidUsernameInvalidPassword(Testcase_Signin.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userValidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userValidUsernameInvalidPassword" time="5.688">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_validUsername_InvalidPassword(Po_Signin.java:124)
at testcase.Testcase_Signin.signIn_userValidUsernameInvalidPassword(Testcase_Signin.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userValidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userValidUsernameInvalidPassword" time="3.519">
    <failure type="java.lang.AssertionError" message="expected [User Doesnt Exist!] but found [Invalid Credentials]">
      <![CDATA[java.lang.AssertionError: expected [User Doesnt Exist!] but found [Invalid Credentials]
at po.Po_Signin.SignIn_validUsername_InvalidPassword(Po_Signin.java:120)
at testcase.Testcase_Signin.signIn_userValidUsernameInvalidPassword(Testcase_Signin.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userValidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userValidUsernameInvalidPassword" time="6.047">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_validUsername_InvalidPassword(Po_Signin.java:124)
at testcase.Testcase_Signin.signIn_userValidUsernameInvalidPassword(Testcase_Signin.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userValidUsernameInvalidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidusernameValidPassword" time="3.824">
    <failure type="java.lang.AssertionError" message="expected [User Doesnt Exist!] but found [Login Success]">
      <![CDATA[java.lang.AssertionError: expected [User Doesnt Exist!] but found [Login Success]
at po.Po_Signin.SignIn_InvalidUsername_validPassword(Po_Signin.java:141)
at testcase.Testcase_Signin.signIn_userInvalidusernameValidPassword(Testcase_Signin.java:79)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidusernameValidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidusernameValidPassword" time="5.409">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_InvalidUsername_validPassword(Po_Signin.java:145)
at testcase.Testcase_Signin.signIn_userInvalidusernameValidPassword(Testcase_Signin.java:79)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidusernameValidPassword -->
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidusernameValidPassword" time="8.27"/>
  <testcase classname="testcase.Testcase_Signin" name="signIn_userInvalidusernameValidPassword" time="5.794">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at po.Po_Signin.SignIn_InvalidUsername_validPassword(Po_Signin.java:145)
at testcase.Testcase_Signin.signIn_userInvalidusernameValidPassword(Testcase_Signin.java:79)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- signIn_userInvalidusernameValidPassword -->
</testsuite> <!-- Testcase_Signin -->
